/*
Batch 73
Nitesh Vijay 2013A7PS164P
Nilay Jain 2013A7PS179P
*/

#include "parser.h"
#include "lexer.h"
#include "ast.h"
#include "symbolTable.h"
#include "typeChecker.h"
#include "codegen.h"
#include  <sys/types.h>

void printcode(tokenInfo* tokenlist)
{
	int lineno = 0;
    while(tokenlist->next!=NULL)
    {
    	if(lineno != tokenlist->lineno)
    	{
    		lineno = tokenlist->lineno;
    		printf("\n");
    		printf("%d :",lineno);
    	}
    	printf("%s ",tokenlist->lexeme);
    	tokenlist = tokenlist->next;
    }
}

void printtoken(tokenInfo* tokenlist)
{
	while(tokenlist->next!=NULL)
	{
		if(tokenlist->isvalid)
			printf("%d : %s (%s)\n",tokenlist->lineno,tokenlist->token,tokenlist->lexeme);
		else
			printf("%d : Invalid token (%s)\n",tokenlist->lineno,tokenlist->lexeme);
		tokenlist = tokenlist->next;
	}
}

int main(int argc, char** args)
{
	int pflag = 0;
	int o;
	pid_t p1 = 0;
	if(argc < 3)
	{
		if(argc<2)
		{
			printf("Need an input program file.\n");
		}
		else
		{
			printf("Need an input program file and an output file.\n");
		}
		exit(0);
	}
	else
	{
		FILE *fp = fopen(args[1],"r");
		if(fp == NULL)
		{
			printf("File not found !!\n");
			exit(0);
		}
		if(argc == 4 && !strcmp(args[3],"-p"))
			pflag = 1;
		
		printf("First and Follow set automated.\n");
		printf("Both lexical and syntax analysis modules implemented.\n");
		printf("Modules work with all the testcases. (Testcase4 prints relevant errors).\n");
		printf("Parse tree is printed to output file given at command line.\n");
		printf("Error recovery in Parsing is implemented.\n\n");
		printf("LEVEL 4: Symbol table/ AST/ Semantic Rules modules work.\n\n");

		
		// while(0)
		// 	{	
		// 		printf("\nPress option for the defined task\n 1 : Print the comment free code on the console.\n 2 : Print the token list (on the console) generated by the lexer.\n 3 : Parse to verify the syntactic correctness of the input source code.\n 4 : Create the parse tree\n 5 : Print AST and Symbol Table \n 6 : Exit \n\n");
		// 		printf("Option : ");
		// 		scanf("%d",&o);
		// 		switch(o)
		// 		{
		// 			case 1:
		// 				printcode(tokenlist);
		// 				printf("\n");
		// 				break;
		// 			case 2:
		// 				printtoken(tokenlist);
		// 				break;
		// 			case 3:
		// 				root = parseInputSourceCode(args[1], &error);
		// 				if(error==0) printf("\nCompiled Successfully: Input source code is syntactically correct!!\n\n");
		// 				else printf("\nCompilation Error\n\n");
		// 				break;
		// 			case 4:
		// 				root = parseInputSourceCode(args[1], &error);
		// 				fp = fopen(args[2], "w");
		// 				printParseTree(root, fp);
		// 				if(error==0) printf("\nCompiled Successfully: Parse tree printed in file %s!!\n\n",args[2]);
		// 				else printf("\nCompilation Error: Parse tree printed in file %s!!\n\n",args[2]);
		// 				fclose(fp);
		// 				break;
		// 			case 5:
		// 				modify_grammar("astRules.txt");
		// 				astTree_root =  construct_ast(root);
		// 				//print_ast(astTree_root);
		// 				astTree_root = clean_ast(astTree_root);
		// 				print_ast(astTree_root);
		// 				printf("\n_____________________________\n");
		// 				symbol_list* lis;
		// 				lis = malloc(sizeof(symbol_list*));
		// 				//lis->next = NULL;
		// 				sym_table* st = createSymbolTable(astTree_root, &lis,1, &error2);
		// 				printSymbolTable(st, lis);
		// 				//print_ast(astTree_root);
		// 				init_typechecker(astTree_root, st,NULL, &error2);
		// 				int parse_tree_size = count_nodes_parser(root);
		// 				int ast_tree_size = count_nodes_ast(astTree_root);
		// 				printf("size of parse tree: %d, size of ast: %d\n", parse_tree_size, ast_tree_size);
		// 				double compression = 100.0 - (double)ast_tree_size/(double)parse_tree_size * 100.0;
		// 				printf("compression percentage: %lf", compression);
		// 				FILE* fp = fopen("code.asm", "w");
		// 				code_gen(astTree_root->children[0],st,lis,fp);
		// 				break;
		// 			default:
		// 				exit(0);
		// 		}
		// 	}
			while(1)
			{
				tokenInfo* tokenlist;
				tokenlist = getNextToken(fp);
				ntree* root = NULL;
				astTree* astTree_root = NULL;
				symbol_list* lis = NULL;
				sym_table* st = NULL;
				int error=0, error2=0;
				parser_init();
				ast_init();
				printf("\nPress option for the defined task\n 1 : Print the token list (on the console) generated by the lexer.\n 2 : Parse to verify the syntactic correctness of the input source code and print parse tree on console.\n 3 : Print AST in Depth first order (On console) \n 4 : Print details of amount of memory and number of nodes for parse tree and AST.\n 5 : Print Symbol table.\n 6 : Compile front end.\n 7 : Produce Assembly code.\n 8 : Exit \n\n");
				printf("Option : ");
				scanf("%d",&o);
				switch(o)
				{
					case 1:
						printtoken(tokenlist);
						return 0;
					case 2:
						if(root == NULL)
							root = parseInputSourceCode(args[1], &error);
						printParseTree(root, stdout);
						if(error==0) printf("\nCompiled Successfully: Input source code is syntactically correct!!\n\n");
						else printf("\nSyntactic Error\n\n");
						return 0;
					case 3:
						if(root == NULL)
						{
							root = parseInputSourceCode(args[1], &error);
							if(error!=0) printf("\nCompilation Error\n\n");
						}
						if(astTree_root==NULL)
						{
							modify_grammar("astRules.txt");
							astTree_root =  construct_ast(root);
							astTree_root = clean_ast(astTree_root);
						}
						print_ast(astTree_root);
						printf("\n\n");
						return 0;
					case 4:
						if(root == NULL)
						{
							root = parseInputSourceCode(args[1], &error);
							if(error!=0) printf("\nCompilation Error\n\n");
						}
						int parse_tree_size = count_nodes_parser(root);
						if(astTree_root==NULL)
						{
							modify_grammar("astRules.txt");
							astTree_root =  construct_ast(root);
							astTree_root = clean_ast(astTree_root);
						}
						int ast_tree_size = count_nodes_ast(astTree_root);
						printf("\nParse tree: Number of nodes = %d Allocated Memory = %ld\n", parse_tree_size, parse_tree_size*sizeof(ntree));
						printf("AST       : Number of nodes = %d Allocated Memory = %ld\n",ast_tree_size,ast_tree_size*sizeof(astTree));
						double compression = 100.0 - (double)ast_tree_size*sizeof(astTree)/((double)parse_tree_size*sizeof(ntree)) * 100.0;
						printf("Compression percentage: %lf\n", compression);
						return 0;
					case 5:
						if(root == NULL)
						{
							root = parseInputSourceCode(args[1], &error);
							if(error!=0) printf("\nCompilation Error\n\n");
						}
						if(astTree_root==NULL)
						{
							modify_grammar("astRules.txt");
							astTree_root =  construct_ast(root);
							astTree_root = clean_ast(astTree_root);
						}
						if(lis==NULL)
							lis = malloc(sizeof(symbol_list));
						if(st == NULL){
							st = createSymbolTable(astTree_root, &lis, 0, &error2);
						}
						printSymbolTable(st, lis);
						return 0;
					case 6:
						printf("Compiling front end ...\n");
						root = parseInputSourceCode(args[1], &error);
						if(error!=0) printf("\nSyntax Error\n\n");
						else if(error == 0)
						{
							if(astTree_root==NULL)
								{
									modify_grammar("astRules.txt");
									astTree_root =  construct_ast(root);
									astTree_root = clean_ast(astTree_root);
								}
							//	if(lis != NULL)
							//		lis = (symbol_list*)realloc(lis,sizeof(symbol_list));
							//	else
								if(lis==NULL)
									lis = malloc(sizeof(symbol_list));
								if(st == NULL)
									st = createSymbolTable(astTree_root, &lis,1, &error2);
								init_typechecker(astTree_root, st,NULL, &error2);
								if(error2!=0)
								{
									printf("\nSemantic Error\n\n");
								}
								else
								{
									printf("Code compiled successfully...\n");
								}
						}
						return 0;
						case 7:
							root = parseInputSourceCode(args[1], &error);
							if(error!=0) printf("\nSyntax Error\n\n");
							else if(error == 0)
							{
								if(astTree_root==NULL)
								{
									modify_grammar("astRules.txt");
									astTree_root =  construct_ast(root);
									astTree_root = clean_ast(astTree_root);
								}
								if(lis ==NULL)
									lis = malloc(sizeof(symbol_list));
								if(st == NULL)
									st = createSymbolTable(astTree_root, &lis,1, &error2);
								init_typechecker(astTree_root, st,NULL, &error2);
								if(error2!=0)
								{
									printf("\nSemantic Error - Assembly code not generated\n\n");
								}
								else
								{
									FILE* code = fopen(args[2], "w");
									code_gen(astTree_root->children[0],st,lis,code);
									printf("\nAssembly code generated in file %s\n",args[2]);
									fclose(code);
									if(strcmp(args[2],"code.asm")==0)
									{
										char ch;
										printf("\nDo you want to run assembly code? (y/n)\n");
										scanf(" %c",&ch);
										if(ch == 'y' || ch == 'Y')
										{
											system("nasm -f elf code.asm -o code.o");
											system("gcc -m32 code.o -o code.out");
											system("./code.out");
										}
									}
								}
							}
							
							return 0;
					default:
						return 0;
				}
			}
		}
}
